# Generated by Django 5.0.6 on 2024-05-31 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucikendaraan', '0002_usercucikuy_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercucikuy',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
