# Generated by Django 5.0.6 on 2024-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucikendaraan', '0004_usercucikuy_groups_usercucikuy_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_date', models.DateField()),
                ('pelanggan', models.CharField(max_length=100)),
                ('jeniskendaraan', models.CharField(choices=[('motor', 'Motor'), ('mobil', 'Mobil')], max_length=50)),
                ('idtransaction', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
