# Generated by Django 5.0.6 on 2024-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucikendaraan', '0006_price_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='jeniskendaraan',
            field=models.CharField(choices=[('motor', 'Motor'), ('mobil', 'Mobil')], max_length=50, unique=True),
        ),
    ]
